services:
  admin-app:
    container_name: adminContainer
    build:
      context: .
      dockerfile: local.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV_VAR=dev
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=admin_dev
    volumes:
      - ./admin:/app
    depends_on:
      mysql-db:
        condition: service_healthy

  mysql-db:
    container_name: adminDb
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin_dev
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  mysql_data: