version: "3.8"

services:
  admin-app:
    container_name: adminContainer
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./admin:/app
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    container_name: adminDb
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: admin_dev # ✅ nombre de la base de datos
      POSTGRES_USER: admin # ✅ usuario
      POSTGRES_PASSWORD: admin # ✅ contraseña
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d admin_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
