version: '3.8' 
services: 
  admin-service:
    container_name: admin-service
    build:
      context: ../admin-service
    ports:
      - "8080:8080"
    environment:
      - ENV_VAR=dev
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=admin_dev
    volumes:
      - ../admin-service:/go/src/app
    depends_on:
      mysql-db:
        condition: service_healthy

  mysql-db:
    container_name: adminDb
    image: mysql:5.7
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin_dev
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
