package seeds

import (
	"fmt"

	"github.com/tiqueteo/adminv2-mock-api/db/models"
	"gorm.io/gorm"
)

func SeedAffiliates(db *gorm.DB) {
	affiliates := []models.Affiliate{
		{
			Status:              "enabled",
			Name:                "Best Deals Co.",
			Description:         "Leading provider of discounted products",
			Website:             "http://www.bestdealsco.com",
			ContactEmail:        "contact@bestdealsco.com",
			VatNumberType:       "EU VAT",
			VatNumber:           "EU123456789",
			ExternalAffiliateId: "BDC001",
			MinimumPayout:       100,
		},
		{
			Status:              "disabled",
			Name:                "GlobalTech Inc.",
			Description:         "Your technology partner for innovation",
			Website:             "http://www.globaltechinc.com",
			ContactEmail:        "info@globaltechinc.com",
			VatNumberType:       "US VAT",
			VatNumber:           "US987654321",
			ExternalAffiliateId: "GTI002",
			MinimumPayout:       200,
		},
		{
			Status:              "enabled",
			Name:                "FashionXpress",
			Description:         "Bringing you the latest fashion trends",
			Website:             "http://www.fashionxpress.com",
			ContactEmail:        "info@fashionxpress.com",
			VatNumberType:       "UK VAT",
			VatNumber:           "UK24681012",
			ExternalAffiliateId: "FX003",
			MinimumPayout:       150,
		},
		{
			Status:              "disabled",
			Name:                "TravelWise",
			Description:         "Your guide to unforgettable adventures",
			Website:             "http://www.travelwise.com",
			ContactEmail:        "hello@travelwise.com",
			VatNumberType:       "CA VAT",
			VatNumber:           "CA2468013579",
			ExternalAffiliateId: "TW004",
			MinimumPayout:       300,
		},
		{
			Status:              "enabled",
			Name:                "FoodForThought",
			Description:         "Delivering culinary delights to your doorstep",
			Website:             "http://www.foodforthought.com",
			ContactEmail:        "info@foodforthought.com",
			VatNumberType:       "AU VAT",
			VatNumber:           "AU9876543210",
			ExternalAffiliateId: "FFT005",
			MinimumPayout:       250,
		},
		{
			Status:              "enabled",
			Name:                "ElectroWorld",
			Description:         "Your source for cutting-edge electronics",
			Website:             "http://www.electroworld.com",
			ContactEmail:        "support@electroworld.com",
			VatNumberType:       "EU VAT",
			VatNumber:           "EU0987654321",
			ExternalAffiliateId: "EW006",
			MinimumPayout:       150,
		},
		{
			Status:              "disabled",
			Name:                "HealthFirst",
			Description:         "Promoting wellness and healthy living",
			Website:             "http://www.healthfirst.com",
			ContactEmail:        "info@healthfirst.com",
			VatNumberType:       "US VAT",
			VatNumber:           "US9876543210",
			ExternalAffiliateId: "HF007",
			MinimumPayout:       200,
		},
		{
			Status:              "enabled",
			Name:                "BookBuddies",
			Description:         "Explore worlds through the pages of a book",
			Website:             "http://www.bookbuddies.com",
			ContactEmail:        "info@bookbuddies.com",
			VatNumberType:       "UK VAT",
			VatNumber:           "UK1234567890",
			ExternalAffiliateId: "BB008",
			MinimumPayout:       100,
		},
		{
			Status:              "disabled",
			Name:                "TechSavvy",
			Description:         "Empowering you with tech solutions",
			Website:             "http://www.techsavvy.com",
			ContactEmail:        "hello@techsavvy.com",
			VatNumberType:       "CA VAT",
			VatNumber:           "CA0987654321",
			ExternalAffiliateId: "TS009",
			MinimumPayout:       300,
		},
		{
			Status:              "enabled",
			Name:                "FitFusion",
			Description:         "Your fitness journey starts here",
			Website:             "http://www.fitfusion.com",
			ContactEmail:        "info@fitfusion.com",
			VatNumberType:       "AU VAT",
			VatNumber:           "AU1234567890",
			ExternalAffiliateId: "FF010",
			MinimumPayout:       200,
		},
		{
			Status:              "enabled",
			Name:                "GadgetGuru",
			Description:         "Unlocking the latest in gadgetry",
			Website:             "http://www.gadgetguru.com",
			ContactEmail:        "support@gadgetguru.com",
			VatNumberType:       "EU VAT",
			VatNumber:           "EU2468013579",
			ExternalAffiliateId: "GG011",
			MinimumPayout:       250,
		},
		{
			Status:              "disabled",
			Name:                "DreamDestinations",
			Description:         "Creating unforgettable travel experiences",
			Website:             "http://www.dreamdestinations.com",
			ContactEmail:        "info@dreamdestinations.com",
			VatNumberType:       "US VAT",
			VatNumber:           "US1234567890",
			ExternalAffiliateId: "DD012",
			MinimumPayout:       300,
		},
		{
			Status:              "enabled",
			Name:                "HomeHarmony",
			Description:         "Transforming spaces into havens",
			Website:             "http://www.homeharmony.com",
			ContactEmail:        "hello@homeharmony.com",
			VatNumberType:       "UK VAT",
			VatNumber:           "UK0987654321",
			ExternalAffiliateId: "HH013",
			MinimumPayout:       150,
		},
		{
			Status:              "disabled",
			Name:                "PetParadise",
			Description:         "Your furry friend's favorite hangout",
			Website:             "http://www.petparadise.com",
			ContactEmail:        "info@petparadise.com",
			VatNumberType:       "CA VAT",
			VatNumber:           "CA1234567890",
			ExternalAffiliateId: "PP014",
			MinimumPayout:       100,
		},
		{
			Status:              "enabled",
			Name:                "StyleSavant",
			Description:         "Unleash your inner style icon",
			Website:             "http://www.stylesavant.com",
			ContactEmail:        "support@stylesavant.com",
			VatNumberType:       "AU VAT",
			VatNumber:           "AU2468013579",
			ExternalAffiliateId: "SS015",
			MinimumPayout:       200,
		},
		{
			Status:              "enabled",
			Name:                "ArtisanAlley",
			Description:         "Where creativity finds its home",
			Website:             "http://www.artisanalley.com",
			ContactEmail:        "info@artisanalley.com",
			VatNumberType:       "EU VAT",
			VatNumber:           "EU1234567890",
			ExternalAffiliateId: "AA016",
			MinimumPayout:       250,
		},
		{
			Status:              "disabled",
			Name:                "TechTrendz",
			Description:         "Stay ahead with the latest tech trends",
			Website:             "http://www.techtrendz.com",
			ContactEmail:        "hello@techtrendz.com",
			VatNumberType:       "US VAT",
			VatNumber:           "US0987654321",
			ExternalAffiliateId: "TT017",
			MinimumPayout:       300,
		},
		{
			Status:              "enabled",
			Name:                "HealthHaven",
			Description:         "Your wellness sanctuary",
			Website:             "http://www.healthhaven.com",
			ContactEmail:        "info@healthhaven.com",
			VatNumberType:       "UK VAT",
			VatNumber:           "UK0987654321",
			ExternalAffiliateId: "HH018",
			MinimumPayout:       100,
		},
		{
			Status:              "disabled",
			Name:                "GourmetGalore",
			Description:         "Elevate your culinary experience",
			Website:             "http://www.gourmetgalore.com",
			ContactEmail:        "info@gourmetgalore.com",
			VatNumberType:       "CA VAT",
			VatNumber:           "CA2468013579",
			ExternalAffiliateId: "GG019",
			MinimumPayout:       150,
		},
		{
			Status:              "enabled",
			Name:                "GreenGrowth",
			Description:         "Sustainable solutions for a better world",
			Website:             "http://www.greengrowth.com",
			ContactEmail:        "support@greengrowth.com",
			VatNumberType:       "AU VAT",
			VatNumber:           "AU9876543210",
			ExternalAffiliateId: "GG020",
			MinimumPayout:       200,
		},
		{
			Status:              "pending",
			Name:                "Discount Deals Ltd.",
			Description:         "Your one-stop shop for great deals",
			Website:             "http://www.discountdeals.com",
			ContactEmail:        "info@discountdeals.com",
			VatNumberType:       "EU VAT",
			VatNumber:           "EU1234567890",
			ExternalAffiliateId: "DDL001",
			MinimumPayout:       100,
		},
		{
			Status:              "pending",
			Name:                "InnovateTech Solutions",
			Description:         "Empowering businesses with innovative solutions",
			Website:             "http://www.innovatetech.com",
			ContactEmail:        "contact@innovatetech.com",
			VatNumberType:       "US VAT",
			VatNumber:           "US9876543210",
			ExternalAffiliateId: "ITS002",
			MinimumPayout:       200,
		},
		{
			Status:              "pending",
			Name:                "Trendy Threads Inc.",
			Description:         "Your source for the latest fashion trends",
			Website:             "http://www.trendythreads.com",
			ContactEmail:        "hello@trendythreads.com",
			VatNumberType:       "UK VAT",
			VatNumber:           "UK2468013579",
			ExternalAffiliateId: "TTI003",
			MinimumPayout:       150,
		},
		{
			Status:              "pending",
			Name:                "Adventure Seekers Ltd.",
			Description:         "Creating unforgettable travel experiences",
			Website:             "http://www.adventureseekers.com",
			ContactEmail:        "info@adventureseekers.com",
			VatNumberType:       "CA VAT",
			VatNumber:           "CA9876543210",
			ExternalAffiliateId: "ASL004",
			MinimumPayout:       300,
		},
		{
			Status:              "pending",
			Name:                "Gourmet Delights Co.",
			Description:         "Delivering gourmet delights straight to your door",
			Website:             "http://www.gourmetdelights.com",
			ContactEmail:        "support@gourmetdelights.com",
			VatNumberType:       "AU VAT",
			VatNumber:           "AU1234567890",
			ExternalAffiliateId: "GDC005",
			MinimumPayout:       250,
		},
	}

	result := db.Create(&affiliates)
	if result.Error != nil {
		fmt.Println("Error seeding affiliates:", result.Error)
	}
}
