package seeds

import (
	"fmt"

	"github.com/tiqueteo/adminv2-mock-api/db/models"
	"gorm.io/gorm"
)

func SeedBoxOffice(db *gorm.DB) {
	boxOffices := []models.BoxOffice{
		{
			Status:                       "enabled",
			Alias:                        "Main Box Office",
			SalesGroupId:                 1,
			BillPrefix:                   "MB",
			InstalledVersion:             "1.0.0",
			OfflineEnabled:               true,
			CashCountThreshold:           100,
			CashCountAttempts:            3,
			AllowSelectMainProduct:       true,
			GroupProductsByCategory:      true,
			ShowOnlyAvailableEvents:      true,
			ShowEventFinalHour:           true,
			OfferNextAvailableSession:    true,
			ShowMaxAvailability:          true,
			AllowPromotionalCodes:        true,
			SellerSelectorEnabled:        true,
			CustomerSelectorEnabled:      true,
			PurchaseFormIntervalNeeded:   15,
			LanguageCode:                 "en",
			PrintTicket:                  true,
			OptionalPrintTicket:          false,
			PrintTicketPrice:             true,
			OptionalPrintTicketPrice:     false,
			PrintSummary:                 true,
			OptionalPrintSummary:         false,
			HighlightPrintedReservations: true,
			SingleDocPrint:               true,
			AllowedTicketGroupTypes:      []string{"individual", "collective"},
			PrintCashCount:               true,
			ShowChangeCalculator:         1,
			AskCashForChange:             true,
			Calculator:                   true,
			ShowDeferredPaymentMethod:    true,
			ValidationMethod:             0,
			VerifierId:                   1,
			AllowConfigPrinter:           true,
			AllowLoginHistory:            true,
			AllowChangePassword:          true,
			AllowSellAndEditPastEvents:   true,
			PrintMultiple:                true,
			CloseDetailsPrintTickets:     true,
			CloseDetailsPrintReceipt:     true,
			AvailabilityThreshold:        10,
		},
		{
			Status:                       "disabled",
			Alias:                        "Secondary Box Office",
			SalesGroupId:                 2,
			BillPrefix:                   "SB",
			InstalledVersion:             "1.0.1",
			OfflineEnabled:               false,
			CashCountThreshold:           50,
			CashCountAttempts:            2,
			AllowSelectMainProduct:       false,
			GroupProductsByCategory:      false,
			ShowOnlyAvailableEvents:      false,
			ShowEventFinalHour:           false,
			OfferNextAvailableSession:    false,
			ShowMaxAvailability:          false,
			AllowPromotionalCodes:        false,
			SellerSelectorEnabled:        false,
			CustomerSelectorEnabled:      false,
			PurchaseFormIntervalNeeded:   10,
			LanguageCode:                 "es",
			PrintTicket:                  false,
			OptionalPrintTicket:          true,
			PrintTicketPrice:             false,
			OptionalPrintTicketPrice:     true,
			PrintSummary:                 false,
			OptionalPrintSummary:         true,
			HighlightPrintedReservations: false,
			SingleDocPrint:               false,
			AllowedTicketGroupTypes:      []string{"total"},
			PrintCashCount:               false,
			ShowChangeCalculator:         0,
			AskCashForChange:             false,
			Calculator:                   false,
			ShowDeferredPaymentMethod:    false,
			ValidationMethod:             1,
			VerifierId:                   2,
			AllowConfigPrinter:           false,
			AllowLoginHistory:            false,
			AllowChangePassword:          false,
			AllowSellAndEditPastEvents:   false,
			PrintMultiple:                false,
			CloseDetailsPrintTickets:     false,
			CloseDetailsPrintReceipt:     false,
			AvailabilityThreshold:        5,
		},
		{
			Status:                       "enabled",
			Alias:                        "Tertiary Box Office",
			SalesGroupId:                 3,
			BillPrefix:                   "TB",
			InstalledVersion:             "2.0.0",
			OfflineEnabled:               true,
			CashCountThreshold:           150,
			CashCountAttempts:            5,
			AllowSelectMainProduct:       true,
			GroupProductsByCategory:      true,
			ShowOnlyAvailableEvents:      true,
			ShowEventFinalHour:           true,
			OfferNextAvailableSession:    true,
			ShowMaxAvailability:          true,
			AllowPromotionalCodes:        true,
			SellerSelectorEnabled:        true,
			CustomerSelectorEnabled:      true,
			PurchaseFormIntervalNeeded:   20,
			LanguageCode:                 "fr",
			PrintTicket:                  true,
			OptionalPrintTicket:          false,
			PrintTicketPrice:             true,
			OptionalPrintTicketPrice:     false,
			PrintSummary:                 true,
			OptionalPrintSummary:         false,
			HighlightPrintedReservations: true,
			SingleDocPrint:               true,
			AllowedTicketGroupTypes:      []string{"collective", "total"},
			PrintCashCount:               true,
			ShowChangeCalculator:         1,
			AskCashForChange:             true,
			Calculator:                   true,
			ShowDeferredPaymentMethod:    true,
			ValidationMethod:             0,
			VerifierId:                   3,
			AllowConfigPrinter:           true,
			AllowLoginHistory:            true,
			AllowChangePassword:          true,
			AllowSellAndEditPastEvents:   true,
			PrintMultiple:                true,
			CloseDetailsPrintTickets:     true,
			CloseDetailsPrintReceipt:     true,
			AvailabilityThreshold:        15,
		},
		{
			Status:                       "enabled",
			Alias:                        "Quaternary Box Office",
			SalesGroupId:                 4,
			BillPrefix:                   "QB",
			InstalledVersion:             "2.1.0",
			OfflineEnabled:               true,
			CashCountThreshold:           200,
			CashCountAttempts:            4,
			AllowSelectMainProduct:       true,
			GroupProductsByCategory:      true,
			ShowOnlyAvailableEvents:      true,
			ShowEventFinalHour:           true,
			OfferNextAvailableSession:    true,
			ShowMaxAvailability:          true,
			AllowPromotionalCodes:        true,
			SellerSelectorEnabled:        true,
			CustomerSelectorEnabled:      true,
			PurchaseFormIntervalNeeded:   25,
			LanguageCode:                 "es",
			PrintTicket:                  true,
			OptionalPrintTicket:          false,
			PrintTicketPrice:             true,
			OptionalPrintTicketPrice:     false,
			PrintSummary:                 true,
			OptionalPrintSummary:         false,
			HighlightPrintedReservations: true,
			SingleDocPrint:               true,
			AllowedTicketGroupTypes:      []string{"individual", "total"},
			PrintCashCount:               true,
			ShowChangeCalculator:         1,
			AskCashForChange:             true,
			Calculator:                   true,
			ShowDeferredPaymentMethod:    true,
			ValidationMethod:             0,
			VerifierId:                   4,
			AllowConfigPrinter:           true,
			AllowLoginHistory:            true,
			AllowChangePassword:          true,
			AllowSellAndEditPastEvents:   true,
			PrintMultiple:                true,
			CloseDetailsPrintTickets:     true,
			CloseDetailsPrintReceipt:     true,
			AvailabilityThreshold:        20,
		},
		{
			Status:                       "disabled",
			Alias:                        "Quinary Box Office",
			SalesGroupId:                 5,
			BillPrefix:                   "QB2",
			InstalledVersion:             "3.0.0",
			OfflineEnabled:               false,
			CashCountThreshold:           75,
			CashCountAttempts:            3,
			AllowSelectMainProduct:       false,
			GroupProductsByCategory:      false,
			ShowOnlyAvailableEvents:      false,
			ShowEventFinalHour:           false,
			OfferNextAvailableSession:    false,
			ShowMaxAvailability:          false,
			AllowPromotionalCodes:        false,
			SellerSelectorEnabled:        false,
			CustomerSelectorEnabled:      false,
			PurchaseFormIntervalNeeded:   30,
			LanguageCode:                 "it",
			PrintTicket:                  false,
			OptionalPrintTicket:          true,
			PrintTicketPrice:             false,
			OptionalPrintTicketPrice:     true,
			PrintSummary:                 false,
			OptionalPrintSummary:         true,
			HighlightPrintedReservations: false,
			SingleDocPrint:               false,
			AllowedTicketGroupTypes:      []string{"collective"},
			PrintCashCount:               false,
			ShowChangeCalculator:         0,
			AskCashForChange:             false,
			Calculator:                   false,
			ShowDeferredPaymentMethod:    false,
			ValidationMethod:             1,
			VerifierId:                   5,
			AllowConfigPrinter:           false,
			AllowLoginHistory:            false,
			AllowChangePassword:          false,
			AllowSellAndEditPastEvents:   false,
			PrintMultiple:                false,
			CloseDetailsPrintTickets:     false,
			CloseDetailsPrintReceipt:     false,
			AvailabilityThreshold:        10,
		},
	}

	result := db.Create(&boxOffices)
	if result.Error != nil {
		fmt.Println("Error seeding affiliates:", result.Error)
	}
}
