package seeds

import (
	"fmt"
	"time"

	"github.com/tiqueteo/adminv2-mock-api/db/models"
	"gorm.io/gorm"
)

func SeedMainPricing(db *gorm.DB) {
	mainPricings := []models.MainPricing{
		{
			MainPricingId: 1,
			StartDatetime: "2024-01-01T00:00:00Z",
			EndDateTime:   "2024-12-31T23:59:59Z",
			ProductId:     2,
		},
		{
			MainPricingId: 2,
			StartDatetime: "2025-01-01T00:00:00Z",
			EndDateTime:   "2025-12-31T23:59:59Z",
			ProductId:     2,
		},
	}

	result := db.Create(&mainPricings)
	if result.Error != nil {
		fmt.Print("There has been an error in the seed of mainPricings")
	}

	specificPricings := []models.SpecificPricing{
		{
			PricingId:     1,
			MainPricingId: 1,
			Name:          "Tarifario Base",
			Priority:      1,
			Weekdays:      []int{1, 2, 3, 4, 5, 6, 7},
			EnabledDates:  []string{},
			Default:       true,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			PricingId:     2,
			MainPricingId: 1,
			Name:          "Tarifario Especial 2024 - Fin de Semana",
			Priority:      2,
			Weekdays:      []int{6, 7},
			EnabledDates:  []string{},
			Default:       false,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			PricingId:     3,
			MainPricingId: 2,
			Name:          "Tarifario Base",
			Priority:      1,
			Weekdays:      []int{1, 2, 3, 4, 5, 6, 7},
			EnabledDates:  []string{},
			Default:       true,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
		{
			PricingId:     4,
			MainPricingId: 2,
			Name:          "Tarifario Especial 2025 - Temporada Alta",
			Priority:      2,
			Weekdays:      []int{1, 2, 3, 4, 5, 6, 7},
			EnabledDates:  []string{"2025-06-01", "2025-06-02", "2025-06-03"},
			Default:       false,
			CreatedAt:     time.Now(),
			UpdatedAt:     time.Now(),
		},
	}
	result = db.Create(&specificPricings)
	if result.Error != nil {
		fmt.Print("There has been an error in the seed of specific pricings")
	}

	productVenueBuyerTypes := []models.ProductVenueBuyerTypes{
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 1,
			PricingId:   1,
			HasDiscount: false,
			Price:       4,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 1,
			PricingId:   1,
			HasDiscount: false,
			Price:       10,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 2,
			PricingId:   1,
			HasDiscount: false,
			Price:       4,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 2,
			PricingId:   1,
			HasDiscount: false,
			Price:       10,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 3,
			PricingId:   1,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 3,
			PricingId:   1,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 4,
			PricingId:   1,
			HasDiscount: false,
			Price:       4,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 4,
			PricingId:   1,
			HasDiscount: false,
			Price:       10,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 5,
			PricingId:   1,
			HasDiscount: false,
			Price:       4,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 5,
			PricingId:   1,
			HasDiscount: false,
			Price:       10,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 6,
			PricingId:   1,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 6,
			PricingId:   1,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 7,
			PricingId:   1,
			HasDiscount: false,
			Price:       4,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 7,
			PricingId:   1,
			HasDiscount: false,
			Price:       10,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 1,
			PricingId:   2,
			HasDiscount: false,
			Price:       4,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 1,
			PricingId:   2,
			HasDiscount: false,
			Price:       10,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 2,
			PricingId:   2,
			HasDiscount: false,
			Price:       4,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 2,
			PricingId:   2,
			HasDiscount: false,
			Price:       10,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 3,
			PricingId:   2,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 3,
			PricingId:   2,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 4,
			PricingId:   2,
			HasDiscount: false,
			Price:       4,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 4,
			PricingId:   2,
			HasDiscount: false,
			Price:       10,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 5,
			PricingId:   2,
			HasDiscount: false,
			Price:       4,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 5,
			PricingId:   2,
			HasDiscount: false,
			Price:       10,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 6,
			PricingId:   2,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 6,
			PricingId:   2,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 7,
			PricingId:   2,
			HasDiscount: false,
			Price:       4,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 7,
			PricingId:   2,
			HasDiscount: false,
			Price:       10,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 1,
			PricingId:   3,
			HasDiscount: false,
			Price:       4,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 1,
			PricingId:   3,
			HasDiscount: false,
			Price:       10,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 2,
			PricingId:   3,
			HasDiscount: false,
			Price:       4,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 2,
			PricingId:   3,
			HasDiscount: false,
			Price:       10,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 3,
			PricingId:   3,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 3,
			PricingId:   3,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 4,
			PricingId:   3,
			HasDiscount: false,
			Price:       4,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 4,
			PricingId:   3,
			HasDiscount: false,
			Price:       10,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 5,
			PricingId:   3,
			HasDiscount: false,
			Price:       4,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 5,
			PricingId:   3,
			HasDiscount: false,
			Price:       10,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 6,
			PricingId:   3,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 6,
			PricingId:   3,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 7,
			PricingId:   3,
			HasDiscount: false,
			Price:       4,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 7,
			PricingId:   3,
			HasDiscount: false,
			Price:       10,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 1,
			PricingId:   4,
			HasDiscount: false,
			Price:       4,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 1,
			PricingId:   4,
			HasDiscount: false,
			Price:       10,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 2,
			PricingId:   4,
			HasDiscount: false,
			Price:       4,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 2,
			PricingId:   4,
			HasDiscount: false,
			Price:       10,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 3,
			PricingId:   4,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 3,
			PricingId:   4,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 4,
			PricingId:   4,
			HasDiscount: false,
			Price:       4,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 4,
			PricingId:   4,
			HasDiscount: false,
			Price:       10,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 5,
			PricingId:   4,
			HasDiscount: false,
			Price:       4,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 5,
			PricingId:   4,
			HasDiscount: false,
			Price:       10,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 6,
			PricingId:   4,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 6,
			PricingId:   4,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			VenueId:     1,
			BuyerTypeId: 7,
			PricingId:   4,
			HasDiscount: false,
			Price:       4,
		},
		{
			ProductId:   2,
			VenueId:     2,
			BuyerTypeId: 7,
			PricingId:   4,
			HasDiscount: false,
			Price:       10,
		},
	}
	result = db.Create(&productVenueBuyerTypes)
	if result.Error != nil {
		fmt.Print("There has been an error in the seed of pricings: product/venue/buyertypes")
	}

	productExtraBuyerTypes := []models.ProductExtraBuyerTypes{
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 1,
			PricingId:   1,
			HasDiscount: false,
			Price:       26,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 2,
			PricingId:   1,
			HasDiscount: false,
			Price:       24,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 3,
			PricingId:   1,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 4,
			PricingId:   1,
			HasDiscount: false,
			Price:       18,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 5,
			PricingId:   1,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 6,
			PricingId:   1,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 7,
			PricingId:   1,
			HasDiscount: false,
			Price:       24,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 1,
			PricingId:   2,
			HasDiscount: false,
			Price:       26,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 2,
			PricingId:   2,
			HasDiscount: false,
			Price:       24,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 3,
			PricingId:   2,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 4,
			PricingId:   2,
			HasDiscount: false,
			Price:       18,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 5,
			PricingId:   2,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 6,
			PricingId:   2,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 7,
			PricingId:   2,
			HasDiscount: false,
			Price:       24,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 1,
			PricingId:   3,
			HasDiscount: false,
			Price:       26,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 2,
			PricingId:   3,
			HasDiscount: false,
			Price:       24,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 3,
			PricingId:   3,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 4,
			PricingId:   3,
			HasDiscount: false,
			Price:       18,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 5,
			PricingId:   3,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 6,
			PricingId:   3,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 7,
			PricingId:   3,
			HasDiscount: false,
			Price:       24,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 1,
			PricingId:   4,
			HasDiscount: false,
			Price:       26,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 2,
			PricingId:   4,
			HasDiscount: false,
			Price:       24,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 3,
			PricingId:   4,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 4,
			PricingId:   4,
			HasDiscount: false,
			Price:       18,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 5,
			PricingId:   4,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 6,
			PricingId:   4,
			HasDiscount: false,
			Price:       0,
		},
		{
			ProductId:   2,
			ExtraId:     1,
			BuyerTypeId: 7,
			PricingId:   4,
			HasDiscount: false,
			Price:       24,
		},
	}
	result = db.Create(&productExtraBuyerTypes)
	if result.Error != nil {
		fmt.Print("There has been an error in the seed of pricings: product/extra/buyertypes")
	}
}
