package seeds

import (
	"fmt"
	"time"

	"github.com/tiqueteo/adminv2-mock-api/db/models"
	"gorm.io/gorm"
)

func SeedSalesGroups(db *gorm.DB) {
	groups := []models.SalesGroup{
		{
			Status:                true,
			Name:                  `{ "en": "Web Sales", "es": "Ventas Web", "ca": "Vendes Web" }`,
			DisplayName:           `{ "en": "Web Sales", "es": "Ventas Web", "ca": "Vendes Web" }`,
			Slug:                  `{ "en": "web-sales", "es": "ventas-web", "ca": "vendes-web" }`,
			Type:                  "WEB_INDIVIDUAL",
			CalendarStatus:        true,
			CalendarType:          "calendar",
			OpeningDate:           time.Date(2023, time.January, 1, 0, 0, 0, 0, time.UTC),
			PeriodType:            "day",
			NumPeriods:            30,
			ClosingDate:           time.Date(2023, time.December, 31, 0, 0, 0, 0, time.UTC),
			MinTickets:            1,
			MaxTickets:            5,
			TicketGroupingType:    "Individual",
			ReservedEmail:         true,
			SendEmailReminder:     true,
			SendEmailCancellation: true,
			ShowPassbookEmail:     true,
			ShowGoogleWalletEmail: true,
			CheckBenefits:         false,
			LoyaltyProgramId:      1,
			MinNumDays:            0,
			PurchaseAfterMinutes:  15,
			EditAfterMinutes:      30,
			Icon:                  "icon-web",
			HiddenOnline:          false,
			OrderSpecialEvents:    "displayOrder",
			InfoMessage:           `{ "en": "Special web sales info", "es": "Información especial de ventas web", "ca": "Informació especial de vendes web" }`,
			DisplayOrder:          1,
		},
		{
			Status:                true,
			Name:                  `{ "en": "Group Bookings", "es": "Reservas de Grupo", "ca": "Reserves de Grup" }`,
			DisplayName:           `{ "en": "Group Bookings", "es": "Reservas de Grupo", "ca": "Reserves de Grup" }`,
			Slug:                  `{ "en": "group-bookings", "es": "reservas-grupo", "ca": "reserves-grup" }`,
			Type:                  "WEB_GROUPS",
			CalendarStatus:        true,
			CalendarType:          "calendar",
			OpeningDate:           time.Date(2023, time.February, 1, 0, 0, 0, 0, time.UTC),
			PeriodType:            "week",
			NumPeriods:            52,
			ClosingDate:           time.Date(2023, time.December, 31, 0, 0, 0, 0, time.UTC),
			MinTickets:            10,
			MaxTickets:            50,
			TicketGroupingType:    "Collective",
			ReservedEmail:         false,
			SendEmailReminder:     true,
			SendEmailCancellation: false,
			ShowPassbookEmail:     false,
			ShowGoogleWalletEmail: false,
			CheckBenefits:         true,
			LoyaltyProgramId:      2,
			MinNumDays:            7,
			PurchaseAfterMinutes:  30,
			EditAfterMinutes:      60,
			Icon:                  "icon-group",
			HiddenOnline:          false,
			OrderSpecialEvents:    "displayOrder",
			InfoMessage:           `{ "en": "Group bookings available", "es": "Reservas de grupo disponibles", "ca": "Reserves de grup disponibles" }`,
			DisplayOrder:          2,
		},
		{
			Status:                false,
			Name:                  `{ "en": "VIP Sales", "es": "Ventas VIP", "ca": "Vendes VIP" }`,
			DisplayName:           `{ "en": "VIP Access", "es": "Acceso VIP", "ca": "Accés VIP" }`,
			Slug:                  `{ "en": "vip-sales", "es": "ventas-vip", "ca": "vendes-vip" }`,
			Type:                  "SELLER",
			CalendarStatus:        false,
			CalendarType:          "periodic",
			OpeningDate:           time.Date(2023, time.March, 1, 0, 0, 0, 0, time.UTC),
			PeriodType:            "month",
			NumPeriods:            12,
			ClosingDate:           time.Date(2023, time.December, 31, 0, 0, 0, 0, time.UTC),
			MinTickets:            1,
			MaxTickets:            10,
			TicketGroupingType:    "Individual",
			ReservedEmail:         true,
			SendEmailReminder:     false,
			SendEmailCancellation: true,
			ShowPassbookEmail:     true,
			ShowGoogleWalletEmail: true,
			CheckBenefits:         true,
			LoyaltyProgramId:      3,
			MinNumDays:            14,
			PurchaseAfterMinutes:  60,
			EditAfterMinutes:      120,
			Icon:                  "icon-vip",
			HiddenOnline:          true,
			OrderSpecialEvents:    "displayOrder",
			InfoMessage:           `{ "en": "Exclusive VIP sales events", "es": "Eventos de ventas VIP exclusivos", "ca": "Esdeveniments de vendes VIP exclusius" }`,
			DisplayOrder:          3,
		},
		{
			Status:                true,
			Name:                  `{ "en": "Early Bird", "es": "Madrugador", "ca": "Madrugador" }`,
			DisplayName:           `{ "en": "Early Bird Specials", "es": "Especiales para Madrugadores", "ca": "Especials per a Madrugadors" }`,
			Slug:                  `{ "en": "early-bird", "es": "madrugador", "ca": "madrugador" }`,
			Type:                  "BOX_OFFICE",
			CalendarStatus:        true,
			CalendarType:          "calendar",
			OpeningDate:           time.Date(2023, time.April, 1, 0, 0, 0, 0, time.UTC),
			PeriodType:            "day",
			NumPeriods:            15,
			ClosingDate:           time.Date(2023, time.December, 31, 0, 0, 0, 0, time.UTC),
			MinTickets:            1,
			MaxTickets:            5,
			TicketGroupingType:    "Individual",
			ReservedEmail:         false,
			SendEmailReminder:     true,
			SendEmailCancellation: false,
			ShowPassbookEmail:     false,
			ShowGoogleWalletEmail: false,
			CheckBenefits:         false,
			LoyaltyProgramId:      4,
			MinNumDays:            1,
			PurchaseAfterMinutes:  5,
			EditAfterMinutes:      10,
			Icon:                  "icon-early-bird",
			HiddenOnline:          false,
			OrderSpecialEvents:    "displayOrder",
			InfoMessage:           `{ "en": "Get your tickets early!", "es": "¡Consigue tus entradas temprano!", "ca": "¡Consegueix les teves entrades dhora!" }`,
			DisplayOrder:          4,
		},
		{
			Status:                true,
			Name:                  `{ "en": "Last Minute", "es": "Último Minuto", "ca": "Últim Minut" }`,
			DisplayName:           `{ "en": "Last Minute Tickets", "es": "Entradas de Último Minuto", "ca": "Entrades dÚltim Minut" }`,
			Slug:                  `{ "en": "last-minute", "es": "ultimo-minuto", "ca": "ultim-minut" }`,
			Type:                  "SELF_SERVICE",
			CalendarStatus:        true,
			CalendarType:          "calendar",
			OpeningDate:           time.Date(2023, time.May, 1, 0, 0, 0, 0, time.UTC),
			PeriodType:            "day",
			NumPeriods:            10,
			ClosingDate:           time.Date(2023, time.December, 31, 0, 0, 0, 0, time.UTC),
			MinTickets:            1,
			MaxTickets:            5,
			TicketGroupingType:    "Individual",
			ReservedEmail:         true,
			SendEmailReminder:     true,
			SendEmailCancellation: true,
			ShowPassbookEmail:     true,
			ShowGoogleWalletEmail: true,
			CheckBenefits:         false,
			LoyaltyProgramId:      5,
			MinNumDays:            0,
			PurchaseAfterMinutes:  0,
			EditAfterMinutes:      5,
			Icon:                  "icon-last-minute",
			HiddenOnline:          false,
			OrderSpecialEvents:    "displayOrder",
			InfoMessage:           `{ "en": "Dont miss out on last-minute deals", "es": "No te pierdas las ofertas de último minuto", "ca": "No et perdis les ofertes dúltim minut" }`,
			DisplayOrder:          5,
		},
	}

	result := db.Create(groups)
	if result.Error != nil {
		fmt.Print("There has been an error in the seed of sales groups")
	}
}
